//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRLLadderERPSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Season
    {
        public int PKFK_TeamID { get; set; }
        public Nullable<int> Season_For { get; set; }
        public Nullable<int> Season_Against { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
