//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRLLadderERPSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int PK_TeamId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Played { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Draw { get; set; }
        public Nullable<int> Lost { get; set; }
        public Nullable<int> Byes { get; set; }
    
        public virtual Ladder Ladder { get; set; }
        public virtual Season Season { get; set; }
    }
}
